blog/urls.py
from django.urls import path

from blog.views import BlogPostListView, BlogPostCreateView, BlogPostUpdateView, \
    BlogPostDeleteView, BlogPostDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogPostListView.as_view(), name='list'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('update/<slug>', BlogPostUpdateView.as_view(), name='update'),
    path('delete/<slug>', BlogPostDeleteView.as_view(), name='delete'),
    path('detail/<slug>', BlogPostDetailView.as_view(), name='detail'),


   ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('users.urls', namespace='users'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=30)
    slug = models.CharField(max_length=30)
    content = models.TextField()
    preview = models.ImageField(upload_to='post_images')
    created_at = models.DateTimeField(auto_now_add=True)
    publication_sign = models.BooleanField(default=True)
    number_of_views = models.IntegerField(default=90)

    def __str__(self):
        return f'Post (pk={self.pk}, name={self.title})'

blog/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, \
    DetailView

from blog.models import BlogPost


# Create your views here.
class BlogPostListView(ListView):
    model = BlogPost

    def get_queryset(self):
        queryset = BlogPost.objects.filter(publication_sign=True)
        return queryset


class BlogPostCreateView(CreateView):
    model = BlogPost
    fields = ('title', 'content', 'preview')
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = new_post.title
            new_post.save()
        return super().form_valid(form)


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    fields = ('title', 'content', 'preview', 'publication_sign')

    def get_success_url(self):
        return reverse('blog:detail', args=[self.kwargs.get('slug')])

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = new_post.title
            new_post.save()
        return super().form_valid(form)


class BlogPostDeleteView(DeleteView):
    model = BlogPost
    success_url = reverse_lazy('blog:list')


class BlogPostDetailView(DetailView):
    model = BlogPost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_of_views += 1
        self.object.save()
        if self.object.number_of_views == 100:
            send_mail(
                subject='Поздравление',
                message=f'Поздравляю ваш пост {self.object.title} набрал 100 просмотров',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=['victoria.gaponava@gmail.com'],
                fail_silently=False,
            )
        self.object.save()
        return self.object

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>
                                Хотите удалить запись "{{ object.title }}"
                            </p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'blog:list' %}" class="btn btn-success">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr class="align-self-lg-center">
                            <img class="card-img-top mb-2" style="width: 75%" src="{% mediapath object.preview %}"/>
                        </tr>
                        <tr>
                            <td class="w-25">Заголовок</td>
                            <td>{{ object.title }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Слаг</td>
                            <td>{{ object.slug }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Содержание</td>
                            <td>{{ object.content }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ID записи</td>
                            <td>{{ object.id }}</td>
                        </tr>
                         <tr>
                            <td class="w-25">Создана</td>
                            <td>{{ object.created_at }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Просмотры</td>
                            <td>{{ object.number_of_views }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

    </div>
{% endblock %}>

blog/templates/blog/blogpost_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
    <div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить запись</a>
    </div>
    <div class="row text-center">
        {% for item in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ item.title }}</h4>
                </div>
                <div class="card-body">
                    <a href="{% url 'blog:detail' item.id %}">
                          <img alt="Фото товара" style="width: 75%" src="{% mediapath item.preview %} "/>
                    </a>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>Содержание: {{ item.content|truncatechars:100 }}</li>
                    </ul>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:detail' item.slug %}" class="btn btn-sm btn-outline-secondary">Подробно</a>
                            <a href="{% url 'blog:update' item.slug %}" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                            <a href="{% url 'blog:delete' item.slug %}" class="btn btn-sm btn-outline-secondary">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    <nav aria-label="...">
  <ul class="pagination">
      {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{% url 'blog:list' %}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            </li>
      {% else %}
          <li class="page-item disabled">
      <a class="page-link" >Предыдущая</a>
    </li>
      {% endif %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'blog:list' %}?page={{ page_obj.next_page_number }}">Следующая</a>
    </li>
    {% else %}
        <li class="page-item disabled">
      <a class="page-link">Следующая</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endblock %}