blog/urls.py
from django.urls import path

from blog.views import BlogPostListView, BlogPostCreateView, BlogPostUpdateView, \
    BlogPostDeleteView, BlogPostDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogPostListView.as_view(), name='list'),
    path('create/', BlogPostCreateView.as_view(), name='create'),
    path('update/<slug>', BlogPostUpdateView.as_view(), name='update'),
    path('delete/<slug>', BlogPostDeleteView.as_view(), name='delete'),
    path('detail/<slug>', BlogPostDetailView.as_view(), name='detail'),


   ]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import contacts, ProductListView, ProductDetailView, ProductCreateView

app_name = 'catalog'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', contacts, name='contacts'),
    path('product/<str:name>/', cache_page(60)(ProductDetailView.as_view()), name='detail_product'),
    path('product/сreate/', ProductCreateView.as_view(), name='create_product')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import blog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  include('catalog.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('users.urls', namespace='users'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.db.models import Q

from users.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return f"{self.name}"


class Product(models.Model):
    class Meta:
        ordering = ("-created_at",)

    name = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='products_images', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_preview(self):
        return self.description.split('-')[1:]


class Contact(models.Model):
    country = models.CharField(max_length=100)
    inn = models.CharField(max_length=18)
    address = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.country} {self.address}"


class Version(models.Model):
    products = models.ManyToManyField(Product, related_name='versions', blank=True)
    number = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms

from catalog.models import Product, Version
from config import settings


class ProductForm(forms.ModelForm):
    version = forms.ModelChoiceField(queryset=Version.objects.all(), required=False,
                                     empty_label="Выберите версию")

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if set(name.lower().split()).intersection(settings.FORBIDDEN_WORDS):
            raise forms.ValidationError("Ошибка связана с названием продукта")
        else:
            return name

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if set(description.lower().split()).intersection(settings.FORBIDDEN_WORDS):
            raise forms.ValidationError("Ошибка связана с описанием продукта")
        else:
            return description


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ('number', 'name', 'is_active')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import formset_factory
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from catalog.models import Product, Contact
from catalog.forms import ProductForm, VersionForm
from catalog.services import get_categories


# Create your views here.
# def home(request):
#     context = {
#         'title': 'SkyStore',
#         'products': Product.objects.all()[:6]
#
#     }
#     return render(request, 'catalog/product_list.html', context=context)

class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        categories = get_categories()
        for product in products:
            product.active_version = product.versions.filter(is_active=True).first()
        context['categories'] = categories
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')

    def form_valid(self, form):
        new_product = form.save()
        new_product.owner = self.request.user
        new_product.save()
        selected_version = form.cleaned_data['version']
        selected_version.products.add(new_product)
        selected_version.save()
        return super().form_valid(form)


def contacts(request):
    context = {
        'title': 'Contacts',
        'contact': Contact.objects.first()
    }
    if request.method == 'POST':
        visiter = {}
        visiter["name"] = request.POST.get('name')
        visiter["phone"] = request.POST.get('phone')
        visiter["message"] = request.POST.get('message')
        print(visiter)
    return render(request, 'catalog/contacts.html', context=context)


# class ContactCreateView(CreateView):
#     model = Contact
#     fields = ['title', 'contact']

# def detail_product(request, pk):
#     product = Product.objects.get(pk=pk)
#     context = {"product": product}
#     return render(request, 'catalog/product_detail.html', context=context)


class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'

    def get_object(self, queryset=None):
        name = self.kwargs.get('name')
        return get_object_or_404(Product, name=name)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object
        product.active_version = product.versions.filter(is_active=True).first()
        context['product'] = product
        return context

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {{title}}
    </title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}
{% block content %}
{% endblock %}
<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{contact.country}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{contact.inn}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{contact.address}}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <input type="submit" value="Отправить"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <img src="/static/img/catalog/logo.jpg" alt="">
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="container">
    <div class="row text-center">
        {% for product in products %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <a href="product/{{product.pk}}">
                        <img src="{{product.image|mediapath}}" alt="" style="max-width: 75%;">
                    </a>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{ product.price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {% for preview in product.get_preview %}
                        <li>-{{ preview }}</li>
                        {% endfor %}
                    </ul>
                    <div class="row">
                        <button type="button" class="btn btn-lg btn-block btn-outline-success w-50">Купить
                        </button>
                        <button type="button" class="btn btn-lg btn-block btn-outline-danger w-50"
                                data-bs-toggle="collapse" data-bs-target="#{{ product.name }}"
                                aria-expanded="false"
                                aria-controls="collapseExample">Ознакомиться
                        </button>
                    </div>
                </div>
                <div class="collapse" id="{{ product.name }}">
                    <div class="card card-body">
                        {{product.description|truncatechars:10}}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends "catalog/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <img src="/static/img/catalog/logo.jpg" alt="">
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="container">
    <div class="row text-center">
        <div class="col-8">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <img src="{{ product.image.url }}" alt="" style="max-width: 75%;">
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ {{ product.price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {% for preview in product.get_preview %}
                        <li>-{{ preview }}</li>
                        {% endfor %}
                    </ul>
                    <div class="row">
                        <button type="button" class="btn btn-lg btn-block btn-outline-success w-50">Купить
                        </button>
                        <button type="button" class="btn btn-lg btn-block btn-outline-danger w-50"
                                data-bs-toggle="collapse" data-bs-target="#{{ product.name }}"
                                aria-expanded="false"
                                aria-controls="collapseExample">Ознакомиться
                        </button>
                    </div>
                </div>
                <div class="collapse" id="{{ product.name }}">
                    <div class="card card-body">
                        {{product.description}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "catalog/base.html" %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <img src="/static/img/catalog/logo.jpg" alt="">
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
<div class="col-12 mx-auto mb-4" style="width: 200px;">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>

</div>
<div class="container">
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <a href="product/{{product.name}}">
                        <img src="{{product.image|mediapath}}" alt="" style="max-width: 75%;">
                    </a>
                </div>
                <div class="card-body">
                    <h1>{{ product.name }}</h1>
                    <h1 class="card-title pricing-card-title">$ {{ product.price }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        {% if product.active_version %}
                        <li>-{{ product.active_version }}</li>
                        {% else %}
                        <li>Нет активной версии</li>
                        {% endif %}
                        {% if product.get_preview %}
                        {% for preview in product.get_preview %}
                        <li>-{{ preview }}</li>
                        {% endfor %}
                        {% else %}
                        <li>-{{ product.description}}</li>
                        {% endif %}
                    </ul>
                    <div class="row">
                        <button type="button" class="btn btn-lg btn-block btn-outline-success w-50">Купить
                        </button>
                        <button type="button" class="btn btn-lg btn-block btn-outline-danger w-50"
                                data-bs-toggle="collapse" data-bs-target="#{{ product.name }}"
                                aria-expanded="false"
                                aria-controls="collapseExample">Ознакомиться
                        </button>
                    </div>
                </div>
                <div class="collapse" id="{{ product.name }}">
                    <div class="card card-body">
                        {{product.description|truncatechars:10}}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}